"""add relationship

Revision ID: 783870cdc0f8
Revises: e8aa52f2bbf3
Create Date: 2024-12-11 02:41:13.106062

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '783870cdc0f8'
down_revision: Union[str, None] = 'e8aa52f2bbf3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
