version: '3.8'

services:
  db:
    container_name: bet_system_postgres
    image: postgres:latest
    environment:
      - POSTGRES_DB=${POSTGRES_DB_NAME}
      - POSTGRES_USER=${POSTGRES_DB_USER}
      - POSTGRES_PASSWORD=${POSTGRES_DB_PASSWORD}
    ports:
      - "${POSTGRES_DB_HOST_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    env_file:
      - .env

  web:
    container_name: bet_system_fastapi
    build:
      context: .
    ports:
      - "${APP_HOST_PORT}:5050"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/app
    restart: always

volumes:
  postgres_data:
